# Form implementation generated from reading ui file '.\ui\login_form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_win_login(object):
    def setupUi(self, win_login):
        win_login.setObjectName("win_login")
        win_login.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(win_login)
        self.centralwidget.setObjectName("centralwidget")
        self.te_login = QtWidgets.QTextEdit(self.centralwidget)
        self.te_login.setGeometry(QtCore.QRect(180, 100, 421, 71))
        self.te_login.setObjectName("te_login")
        self.te_pass = QtWidgets.QTextEdit(self.centralwidget)
        self.te_pass.setGeometry(QtCore.QRect(180, 280, 421, 71))
        self.te_pass.setObjectName("te_pass")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 70, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(300, 420, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 360, 111, 41))
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setObjectName("pushButton_2")
        win_login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(win_login)
        self.statusbar.setObjectName("statusbar")
        win_login.setStatusBar(self.statusbar)

        self.retranslateUi(win_login)
        QtCore.QMetaObject.connectSlotsByName(win_login)

    def retranslateUi(self, win_login):
        _translate = QtCore.QCoreApplication.translate
        win_login.setWindowTitle(_translate("win_login", "Вхід"))
        self.label.setText(_translate("win_login", "Логін (email або номер телефону)"))
        self.label_2.setText(_translate("win_login", "Пароль"))
        self.btn_login.setText(_translate("win_login", "Увійти"))
        self.pushButton_2.setText(_translate("win_login", "Зареєструватися"))
